server:
  port: 9009

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MohammedImranKhan8133/config-server
          clone-on-start: true